#!/bin/bash

sed -i 's/Init \([-+][0-9][0-9]*\);/**init**\1;/' $1
sed -i 's/darkvision \([0-9][0-9]*\) ft./drkvis\1 /' $1
sed -i 's/low-light vision/ll-vis/' $1
sed -i 's/Perception \([+-][0-9][0-9]*\)/**perc**\1/' $1
sed -i 's/Fort \([+-][0-9][0-9]*\), Ref \([+-][0-9][0-9]*\), Will \([+-][0-9][0-9]*\)/**f**\1\/**r**\2\/**w**\3/' $1
sed -i 's/AC \([0-9][0-9]*\), touch \([0-9][0-9]*\), flat-footed \([0-9][0-9]*\) ([^(]*)/**ac**\1 (t\2, ff\3)/' $1
sed -i 's/hp \([0-9][0-9]*\) ([^(]*)/**hp**\1/' $1
