<u>Barghest, Greater</u>  
**lrg**; **init**+6; drkvis60, scent, **perc**+16; **ac**20 (t11, ff18); **hp** 85; **f**+9/**r**+10/**w**+10; **dr**10/mag; **sp**40; **bite** +14/1d8+6, **2 claws** +14/1d6+6; **cmb/d**+16/28(32 trip); *Best 27*  
**spells** (cl9, conc+8): aw-blink, invisibility sphere, levitate, misdirection; 1/d-charm monster (dc18), crushing despair (dc18), dimension door, mass bull's strength, mass enlarge  
**special**: combat ref(+2), change shape (goblin or wolf, as polymorph)  

<u>Bruthazmus</u>  
**init**+3; drkvis60, scent, **perc**+1; **ac**19 (t13, ff16); **hp** 31; **f**+6/**r**+8/**w**+2; **sp**30; **hvy flail** +7/1d10+6/19 or **mw c.longbow** +8/1d8+4/x3; **cmb/d**+7/20; *RotRLAA* 52  
**special**: fav enemy (elves+2); point-blank shot; track+1; wld emp +0  
**gear**: 4 +1 elf bane arr, pot cure mod wnds, stdd lth, hvy flail, mw c.longbow, 20 arr, 4pp  

<u>Bunyip</u>  
**init**+3; drkvis60, llvis, keen scent(180), **perc**+8; **ac**15 (t13, ff12); **hp** 32; **f**+5/**r**+7**w**+1; **sp**10, **sw**40; **bite** +7/1d8+1/19(+bleed(1d6)); **cmb/d**+6/19; *Best2 50*  
**special**: roar (std act, 100' >=4hd w:dc13 or panicked 2d4r), blood frenzy (when smell bood in water, may rage for 1m: +2con, +2str, -2ac)*  

<u>Captain Ashferth</u> cr7; xp3,200; hum ftr 8  
**init**+5; **perc**–2; **ac**23 (t14, ff21); **hp**72; **f**+8/**w**+3/**r**+0(+2v fear); **sp**30; **+1 lngswd** +15/+10/1d8+8/17 or **mw sh swd** +13/+8/1d6+4/19; **cmb/d**+12/26; *No Resp fm Deepmar 25*  
Str 18, Dex 13, Con 14, Int 10, Wis 6, Cha 13
**special**: pwr atk (-3/+6); cleave (after full atk hits, make 2nd atk @full BAB @another foe, -2ac until nxt turn); spr atk (mv>=10, atk, & can mv again, no aoo frm tgt)  
**gear**: pot bear end, pot bull str, +1 brstplt, mw lt stl shld, +1 lngswd, mw sh swd, ring prot +2  

<u>Cave Fisher, Ancient</u> cr9; xp6,400  
**lrg**; **init**+0; drkvis60, **perc**+0; **ac**24 (t9, ff24); **hp**104; **f**+12/**r**+3/**w**+3; **imm** mind-affect; **sp** 20, **cl**20; **2 claws** +14/1d6+4, or **filament** +7tch (60', drag); **rch**10; **cmb/d**+16(+20 w/pull)/26(38 v. trip); *No Resp fm Deepmar* 17  
**special**: filament (str:dc20 or EscArt:dc20 pull free, ac18 (t10), hp20, dr15/slsh); pull (filament, 10'); climb +15  

<u>Chirurgeon Table</u> cr9; xp6,400  
*lrg*; **init**+1; drkvis60, ll-vis, **perc**-5; **ac**20 (t10, ff19); **hp**96; **f**+4/**r**+5/**w**-1; **hardness**10; **imm** construct trts; **sp**40; **2 scalpels** +17/1d6+6/19, **2 syringes** +17/1d2+3+poison, **strap** +17/1d3+3 nonlethal + grab; **reach**10; **cmb/d**+19(+23grap)/30; *No Resp fm Deepmar* 27  
**special**: constrict (1d3+6 nonlethal), poison (2 doses, f:dc14, freq 1/r for 2r, 1 con & unconcious for 1d3h, cure 1 save)  

<u>Cytillipede</u> cr6; xp2,400  
*lrg*; **init** 5; drkvsn60, ll-vis, **perc**+7; **ac**21 (t10, ff20); **hp**84; **f**+10/**r**+7/**w**+2; **imm** mind-affecting; **sp**40, **cl**40; **bite** +13/2d6+7+poison; **reach**5 **cmb/d**+14/25 (can't be tripped); *No Resp fm Deepmar* 29  
**special**: poison (f:dc20, freq 1/r for 6r, 1d3 dex & dazed, cure 1 save); cytillesh flash (1/d, flash bright light in 20' rad & dim light in 40' rad, w:dc22, creatures in 20' rad stunned for 1d4r, in 40' rad confused for 1d2r)  

<u>Cytillesh Zombie</u> cr1; xp400  
**init**+4; drkvis60, **perc**+0; **ac**18 (t12, ff14); **hp**12; **f**+0/**r**+4/**w**+3; **sp**40; **slam** +6/1d6+5+poison; **cmb/d**+6/20; *No Resp fm Deepmar* 20  
**special**: chnl resis +4, quick strikes (when taking full attack, can take extra slam atk @ highest bonus), cytellish poinson (slam, f:dc18, dazed 1d3r, mult poisonings extend duration)  

<u>Daris Hulior</u> cr5 ; xp1,600; hum ftr 4  
**init**+5; detect mag, **perc**-1; **ac**16 (t12 ff14), **hp**67; **f**+8/**r**+5/**w**+3(+5v fear); **sp**30; **hvy pk** +9/+4/1d6+4/x4; **cmb/d**+9/21; *No Resp fm Deepmar 19*  
**spells** (cl8, conc+9): aw---confusion (dc17, 1 tgt only), daze monster (dc 15, no HD lmt), inf srs wnds (dc16)  
3/d---cur mod wnds, glb invuln  
**gear**: mw ch shrt, hvy pick  

<u>Dark Creeper</u> cr2; xp400  
**init**+3; see in drk, **perc**+4; **ac**16 (t14, ff13); **hp**19; **f**+3/**r**+6/**w**+1; **sp**30; **dagger** +6/1d3(+poison)/19; **cmb/d**+1/14; *Best 53*  
**special**: snk atk (+1d6), death throes (flash of light when slain; 10' burst, f:dc13 or blinded 1d6r; darkfolk auto-fail), perfect vision in dark (even magical), light blindness (blinded for 1r, dazzled (-1 atk), while still in bright light), stealth+16, black smear (poison, injury, f:dc15, freq 1/r for 6r, 1d2 str, cure 1 sv)  
**spells** (cl3, conc+2): aw-darkness, detect magic  
**gear**: dagger, black smear x3  

<u>Dark Creeper Skirmisher</u> cr3; xp800; dark creeper rog1  
**init**+3; see in drk, **perc**+10; **ac**16 (t14, ff13); **hp**26; **f**+3/**r**+6/**w**+2; **sp**30; **mw dagger** +7/1d3+1(+poison)/19; **cmb/d**+2/15; *Drkst Veng 12*  
**special**: snk atk (+2d6), death throes (flash of light when slain; 10' burst, f:dc13 or blinded 1d6r; darkfolk auto-fail), perfect vision in dark (even magical), light blindness (blinded for 1r, dazzled (-1 atk), while still in bright light), stealth+16, black smear (poison, injury, f:dc15, freq 1/r for 6r, 1d2 str, cure 1 sv)  
**spells** (cl3, conc+2): aw-darkness, detect magic  
**gear**: mw dagger, black smear x3  

<u>Derro</u> cr3; xp800  
**init**+6; drkvis60, **perc**+0l **ac**17 (t13, ff15); **hp**25; **f**+5/**r**+3/**w**+6; **sr**14; **sp**20; **sh swd** +5/1d4 or **rpt lt xbow** +5/1d6+poison/19 or **aklys** +5/1d6; **cmb/d**+1/13; *Best 70*  
**spells** (cl3, conc+6): aw-darkness, ghost sound(dc13); 1/d-daze(dc13), sound burst(dc15)  
**special**: snk atk (+1d6); vuln to sun (1 con dmg/h in sunlight); poison use (can't accidentally poin self); spider poison (injury, f:dc14, freq 1/r for 4r; 1d2 str dmg; cure 1 save);  

<u>Derro Scout</u> cr7; xp3,200; derro rogue 4  
**init**+9; drkvis60, **perc**+8; **ac**22 (t16, ff17); **hp**66; **f**+6/**r**+10/**w**+7; **sp**20; **sr**18; **mw sh sword** +12/1d4+2/19 or **mw blowgun** +11/1+poison or **+1 rpt lt xbow** +12/1d6+1/19; **cmb/d**+6/17; *No Resp fm Deepmar* 14  
**spells** (cl3, conc+6): aw-darkness, ghost sound(dc13); 1/d-daze(dc13), sound burst(dc15)  
**special**: cmbt ref (+5); bleeding snk atk (+2d6 +2 bleed); stealth +21; fast stealth (mv full sp w/o stealth penalty); evasion (ref saves for ½ do no dmg instead); uncanny dodge (can't be caught flat-footed); vuln to sun (1 con dmg/h in sunlight); poison use (can't accidentally poin self); spider poison (injury, f:dc14, freq 1/r for 4r; 1d2 str dmg; cure 1 save); cytillesh extract (poison, ingested or injury, f:dc18, freq 1/h for 8h, lose memory of events that took place in prev h & can't form new mem for 8h; lost & prevented mem might return later as dreams, & can be returned with restoration or heal spell, cure 2 sv)  
**gear**: +1 std lthr, +1 rpt lt xbow, mw blowgun, mw sh swd, cytillesh extract x5  

<u>Firepelt Cougar</u>  
**init**+5; llvis, scent, **perc**+5; **ac**19 (t16, ff13); **hp** 26; **f**+6/**r**+9/**w**+2; **sp**50, sprint; **bite** +6/1d6+3(+trip), **2 claws** +6/1d3+3; **cmb/d**+6/22(26v trip); *RotRLAA* 43  

<u>Flesh Golem</u> cr7; xp3,200  
**lrg**; **init**-1; drkvis60, llvis, **perc**+0; **ac**20 (t8, ff20); **hp**79; **f**+3/**r**+2/**w**+3; **dr**5/adamant; **imm** see special
**sp**30; **2 slams** +13/2d8+5; **rch**10; **cmb/d**+15/24;  *Best 160*  
**special**: berserk (cum 1%/r atks nearest living crtr or smashes obj smaller than itself, then moving to atk again, creator within 60' may regain control cha:dc19); immunity (mind-affecting effects, bleed, disease, death effects, necro effects, paralysis, psn, sleep, stun, ability dmg/drain, fatigue, exhaustion, engy drain, nonlethal dmg, effects req fort save, massive dmg, spells w/sr; magic ~~cold~~ or ~~fire~~ slows (staggered, can only make mv(½sp) or std act, -1 atk, ac, & ref) for 2d6r, magic ~~elec~~ ends slow & gains 1hp/3dmg)  

<u>Ghast</u> cr2; xp600  
**init**+4; drkvsn60, **perc**+9; **ac**18 (t16, ff16); **hp**17; **f**+4/**r**+4/**w**+7; **sp**30; **bite** +5/1d6+3+disease+paral, **2 claws** +5/1d6+3+paral; **cmb/d**+4/18; *Best* 146, 294  
**special**: chnl resist+2; paralysis (1d4+1r d:dc17); disease (f:dc17; onset 1d; freq 1/d; 1d3 con & 1d3 dex, rise as ghoul if dead; cure 2 consec. sav); stench (10', f:dc15 or sickened 1d6+4m)  

<u>Ghast Lord</u> cr5; xp1,600  
**init**+9; drkvsn60, **perc**+13; **ac**20 (t15, ff15); **hp**57; **f**+7/**r**+7/**w**+9; **sp**30; **bite** +9/1d6+4+disease+rigor mortis, **2 claws** +9/1d6+4+rigor mortis; **cmb/d**+8/23; *MF: Ghouls* 4  
**spells** (cl3, conc+8): 2nd—hold person (dc17), inflict mod wnds (dc17); 1st—bane (dc16), cause fear (dc16), inflict lt wnds x2 (dc16); 0(aw)—bleed (dc15), detect magic, guidance, read magic  
**special**: chnl resist+4; disease (f:dc18; onset 1d; freq 1/d; 1d3 con & 1d3 dex, rise as ghoul if dead; cure 2 consec. sav); stench (10', f:dc18 or sickened 1d6+4m); chnl neg eng (8/d, 2d6, w:dc16); rigor mortis (-2 dex, f:dc18 negates, stacks, paralysed if dex<1, regain 1 dex/m if no further injury, crit=-4 dex save for -2)  

<u>Ghoul</u> cr1; xp400  
**init**+2; drkvsn60, **perc**+7; **ac**14 (t12, ff12); **hp**13; **f**+2/**r**+2/**w**+5; **sp**30; **bite** +3/1d6+1+disease+paral, **2 claws** +3/1d6+1+paral; **cmb/d**+2/14; *Best* 146  
**special**: chnl resist+2; paralysis (1d4+1r d:dc13, elves immune); disease (f:dc13; onset 1d; freq 1/d; 1d3 con & 1d3 dex, rise as ghoul if dead; cure 2 consec. sav)  

<u>Giant Centipede</u> cr½; xp200  
**init**+2; drkvis60, **perc**+4; **ac**14 (t12, ff12); **hp**5; **imm* mind-affect; **f**+3/**r**+2/**w**+0; **sp**40, **cl**40; **bite** +2/1d6-1+psn; **cmb/d**-1/11 (no trp); *Best 43*  
**special**: poison (bite; f:dc13; 1/r for 6r; 1d3 Dex dmg; cure 1 sv); climp +10; stealth +10  

<u>Giant Geko</u>  
**init**+6; llvis **perc**+6; **ac**14 (t12, ff12); **hp** 11; **f**+4/**r**+5/**w**+2; **sp**40, **cl**40; **bite** +2/2d4+1; **cmb/d**+2/14(18v trip); *Best3* 186  

<u>Giant Geko, Advanced</u>  
**init**+8; llvis **perc**+2; **ac**18 (t16, ff16); **hp** 15; **f**+6/**r**+7/**w**+4; **sp**40, **cl**40; **bite** +4/2d4+3; **cmb/d**+4/18(22v trip); *Best3* 186  

<u>Giant Hermit Crab</u>  
**init**+3; drkvis60, **perc**+2; **ac**20 (t13, ff17); **hp** 51; **f**+9/**r**+5/**w**+4; **imm** mind-affecting; **sp**30, **cl**10, **sw**20; **2 claws** +10/1d4+6(+grab); **cmb/d**+10(+14grp)/23(35v trip); *RotRLAA* 63  
**special**: constrict (1d4+6), wtr dep  

<u>Goblin</u>  
**init**+6; drkvis60, **perc**-1; **ac**16 (t13, ff14); **hp** 6; **f**+3/**r**+2/**w**-1; **sp**30; **dogslicer** +3/1d4+1/19; **sh bow** +4/1d4/x3; **cmb/d**+0/12; *Best 156*  

<u>Goblin Brute</u>  
**init**+3; drkvis60, **perc**+0; **ac**16 (t12, ff13); **hp** 63; **f**+8/**r**+4(+1v traps)/**w**+3; **sp**45; **bite** +8/1d3+12, mw grtax +10/1d10+12/x3; **cmb/d**+8/19; *Perram's Goblins* 3  
**special**: imp uncanny ddg (keep dex + to ac when ff, can't be flanked unless atkr lvl>=9); pwr atk (-2/+4); swap places (trade places w/ally w/this feat during mvmnt)  
**gear**: alch fr x3; mw chn sht, mw grtax, shortspear x2  

<u>Goblin Boomer</u>  
**init**+4; drkvis60, **perc**+7; **ac**14 (t14, ff11); **hp** 36; **f**+5/**r**+8/**w**+0; **sp**20; **bomb**(dc15) +9/3d6+3 fire(splash)/x2 or **scrap bmb**(dc15) +9/3d6+3 +3 bleed (ref neagtes)/x2 or **immolation bmb**(dc15) +9/1d6+3 fire for 3rnds (full rnd ref neagtes)/x2; **cmb/d**+2/15; *Perram's Goblins* 4  
**special**: mutagen (+2 nat. arm & +4/-2 to str/int, dex/wis, or con/cha for 50m); pt blnk sht (+1 atk & dmg within 30'); precise bombs (select 3 squares to not be affected by splash effects); precise shot (no -4 for thrw into melee); ricochet splsh wpn (make atk w/splsh wpn if it misses & lands in an occupied sqr)  
**spells** (cl5): 2nd (3/d)---cat's grace, blur, defensive shock; 1st (5/d)---shield, jump, abjuring step, linebreaker, targeted bomb admixture  

<u>Goblin Commando</u>  
**init+3**; drkvi60 ft, **perc**+5; **ac**17 (t14, ff14); **f**+4/**r**+5/**w**+2; **sp**30; **mw horsechopper** +4/1d8+1; **sh bow**  +5/1d4/x3; **cmb/d**+1/14; *RotRLAA* 18  
**special**: fav enemy (animals+2); mounted combat  
**gear**: pot cure mod wnds, stdd leat, mw horsechopper, sh bow, 20 arr  

<u>Goblin Dog</u>  
**init**+2; llvis, scent, **perc**+1; **ac**13 (t12, ff11); **hp** 9; **f**+4/**r**+4/**w**+1; **imm** disease; **sp**50; **bite** +2/1d6+3(+allergic reaction); **cmb/d**+2/14; *Best* 157  
**special**: allergic reaction (f:dc12 or -2dex, -2cha for 1d (rm disease or mag. heal. cures instantly))*  

<u>Goblin Dog, Elite</u>  
**init**+6; llvis, scent, **perc**+6; **ac**19 (t16, ff13); **hp** 32; **f**+9/**r**+9/**w**+3; **imm** disease; **sp**50; **bite** +9/1d6+10(+allergic reaction); **cmb/d**+9/25; *Perram's Goblins* 5  
**special**: allergic reaction (f:dc17 or -2dex, -2cha for 1d (rm disease or mag. heal. cures instantly))*; swap places (trade places w/ally w/this feat during mvmnt)  

<u>Goblin Slicer</u>  
**init**+5; drkvis60, perc+7; **ac**17 (t14, ff 11); **hp** 31; **f**+2/**r**+9(+1v traps)/**w**+0; **sp**20; **2 mw dagger** +8/1d3+1/19; **cmb/d**+3/16; *Perram's Goblins* 2  
**special**: bleeding snk atk (+3d6 +3 bleed); ambush (if can act in sprs rnd, take mv, std & swft acts); evasion (if succeed ref sv for ½ dmg, take none instead); roll with it (if hit & if pass acrobatics chk (dc=5+dmg), mv in desired dir 1'/pt of dmg (rnd up to nearest 5), staggered after attempt); acrobatics +10; swap places (trade places w/ally w/this feat during mvmnt)  
**gear**: caltrops (vicious) x4, mw std lthr, mw dagger x2, shortspear x2  

<u>Goblin Warchanter</u>  
**init**+4; drkvis60, **perc**5; **ac**18 (t15, ff14); **hp** 9; **f**+1/**r**+6/**w**+3(+4 v fear & charm); **sp**30; **dogslicer** +1/1d4/19, or **whip** +1/1d2(nonlethal), or **sh bow** +6/1d4+1/x3; **cmb/d**-2/12; *RotRLAA* 17  
**spells** (cl1, conc+2): 1st(2/d)---cure light wounds, hideous laughter (dc12); 0(aw)---daze (dc11), ghost sound (dc11), mage hand, message  
**special**: brd perf 5r/d (countersong, distraction, facinate, insp courage+1), brd know+1  
**gear**: pot cure lt wnds, stdd lthr, dogslicer, sh bow, 20 arr, whip, 20 gp  

<u>Gogmurt</u>  
**init**+3; dkvis60, **perc**+3; **ac**18 (t15, ff14); **hp** 39; **f**+7/**r**+7/**w**+8 (+4v fey & plant-targeted effects); **sp**30; **flame blade** +3/1d8+2(fire) or **spear** +3/1d6-1/x3, or **sling** +7/1d3-1; **cmb/d**+1/15; *RotRLAA* 43  
**special**: wld shp 1/d; snk atk +1d6; combat casting; nat bnd (animal companion); nat sns; wld emp+4; trackless stp; trapfinding +1; woodland stride  
**spells** (cl4, conc+7): 2nd---animal messenger, flame blade, lssr restoration (already cast); 1st---charm animal (dc14), cure lght wnds, entangle (dc14), speak w/animals; 0(aw)---flare (dc13), guidance, mending, stabilize  
**gear**: pot cure lght wnds (x2), wnd produce flame (34chg), wnd tree shape (4chg), +1 lthr armor, sling, spear, clk of resistance +1  

<u>Gravvik the Cruel</u> cr9; xp6,400; derro sorc7  
**init**+8; drkvis60, **perc**+2; **ac**19 (t17, ff15); **hp**87; **f**+8/**r**+7/**w**+13; **sr**20; **sp**20; **+1 aklys** +11/1d6+psn or **mwk injection spr** +11/1d6-1+psn; **cmb/d**+3/17; *No Resp fm Deepmar* 25  
**spells** (cl3, conc+12): aw---darkness, ghost sound(dc16); 1/d-daze(dc16), sound burst(dc18)  
(cl7, conc+12): 8/d---acidic ray (30' 1d6+3 ~~acid~~); 3rd(5/d)---hold person (dc19), lightning bolt (dc19, 7d6 ~~elec~~), tongues; 2nd(8/d)---alter self, bull's strength, invisibility, see invisibility; 1st(8/d)---charm person (dc17), enlarge person, hypnotism (dc17), mage armor, ray of enfeeblement, shield; 0(aw)---acid splash, bleed (dc16), dancing lights, detect magic, detect poison, mage hand, message  
**special**: snk atk (+1d6); long limbs (+5' rch on tch atk); poison use (can't accidentally poin self); vuln to sun (1 con dmg/h in sunlight); cytillesh extract (psn, ingst or inj, f:dc18, freq 1/h for 8h, lose memory of events that took place in prev h & can't form new mem for 8h; lost & prevented mem might return later as dreams, & can be returned with restoration or heal spell, cure 2 sv); blue whinnis (psn, inj, f:dc16, freq 1/r for 2r, 1 con & unconcious for 1d3h, cure 1 save); stealth +15  
**gear**: blue whinnis x6, cytillesh extract x4, pot cur srs wds x2, scl fireball (cl7), scl haste, +1 aklys, mw injection spr, handy haversack, rng prot +2, key to lock in B13  

<u>Gug</u> cr10; xp9,600  
**lrg**; **init**+1; drkvis60, **perc**+27; **ac**24 (t10, ff23); **hp**127; **f**+9/**r**+6/**w**+12; **imm** disease & psn; **sp**40, **cl**20; **bite** +17/1d8+7, **4 claws** +17/1d6+7; **rch**15; **cmb/d**+19/30; *Best2 151*  
**special**: awesome blow (std act, maneuver v. smaller tgt, tgt takes dmg & knocked back 10' & is prone (1d6 dmg if knocked into obst.)); rend (2 claws, 1d6+10); compression (move through 5' space without squeezing); lunge (+5' rch for 1r, -2 ac); pwr atk (-3/+6); cmd ref (+1); gtr bull rsh (+4 cmb, +2 cmd, doesn't provoke, victim's mv provokes); bld-ft; climb +15; stealth +15  

<u>Intellect Devourer</u> cr8; xp4,800
**init**+10; blndst60, detect mag, **perc**+19; **ac**22 (t17, ff16); **hp**84; **f**+7/**r**+8/**w**+8; **dr**10/adamant & magic; **imm** ~~fire~~, mind-affect;  **resist~~ 20~~cold~~, 20~~elec~~, 20~~sonic~~; **sr**23; **sp**40; **4 claws** +13/1d4+1; **cmb/d**: +6/22(26 v. trp); *Best 180*  
**spells** (cl8): aw---confusion (dc17, single tgt), daze monster (dc15, no HD lmt), inf srs wnds (dc16), invis, reduce person (slf only); 3/d---cure mod wnds, globe of invulnerability;  
**special**: snk atk (+3d6); vuln to prot frm evil (spell treats as summoned creature); telepathy 100'; body thief (As a full-round act (provokes), can reduce size, crawl into mouth of helpless or dead creature, & burrow into skull, devouring brain. This is a coup de grace attempt (8d4+3d6+8). If victim slain (or already dead), int dev takes control of body & may use it (as if controlled by a dominate monster spell). Int dev has full access to host's def & offen abilities (except spells & SLAs (may use own SLAs)). Host may not have been dead for > 1d. Successfully inhabited bodies decay to uselessness in 7d. When occupying body, knows & speaks langs known by host, & basic info about victim's identity & personality. No specific memories or knowledge. Dmg to host doesn't harm int dev. If host slain, int dev emerges & dazed for 1r)  

<u>Klangin</u> cr7; xp3,200; ½orc bbn4/rog4  
**init**+3; blndsght60, fngl sght, **perc**+8; **ac**13 (t11, ff10); **hp**93; **f**+9/**r**+8/**w**+1; **sp**40; **bite** +6/1d4+2, **unarmed** +11/+6/1d3+4; **cmb/d**+11(+13v grap)/22(24v grap); *No Resp fm Deepmar 26*  
**special**: evasion (ref saves for ½ do no dmg instead); imp uncanny dodge (can't be caught flat-footed, or flanked), orc fercty (mv or atk once after <0 hp), trpfnd+2; imp grap (no aoo); imp unrmd stk (no aoo); pwr atk (-2/+4); pwerfl blw (+2 on 1 dmg roll); snk atk (+2d6); fungal sight (see cytillesh taint (or lack of), 60'); vomit (std act/1d3r, rng tch (+10/10'), f:dc17 or tgt nauseated, otherwise sickened)  

<u>Lyrie Akenja</u>  
**init+3**; **perc**+2; **ac**18 (t14, ff14); **hp** 24; **f**+3/**r**+5/**w**+5; **sp**30; **dagger** +1/1d4-1/19-20; **cmb/d**+1/15; *RotRLAA* 59  
**special**: hand of the apprentice (6/d); arcane bond (cat)  
**spells** (cl4, conc+7): 2nd—invisibility, mirror image, shatter (dc16); 1st—burning hands (dc15), grease (dc14), mage armor, ray of enfeeblement; 0(aw)—acid splash, detect magic, prestidigitation, ray of frost  
**gear**: pot cure lght wnds, scr comprehend lang, scr min image, scr see inv, scr sleep, scr whispering wind, wnd magic missile (38chg), dagger, clk resistance +1, silver comb (25gp), fine silk gown (60gp), everburning torch, small pouch of artifacts (hair, fingernail clipping, used handkerchiefs, and a pearl earring (50gp)), 3pp, 278gp, spellbook (all prep, comprehend languages, detect secret doors, floating disc, identify, locate object, minor image, obscuring mist, see invisibility, sleep, spider climb)  

<u>Mite Bodyguard Slave</u> cr2; xp600; mite warrior 3  
**init**+1; drkvsn120, llvis, scent, **perc**+5; **ac**12 (t12, ff11); **hp**19; **f**+3/**r**+4/**w**+4; **dr**2/cldFe;  **sp**20, **cl**20; **dagger** +4/1d3-1/19 or **dart** +5/1d3-1; **cmb/d**–2/9; *Cassomir's Locker* 10  
**spells** (cl1,): aw-prestidigitation; 1/d-doom (dc10)  
**special**: hatred (+4 atk against dwarves & gnomes); pnt-blnk sht (+1 atk & dmg on rngd atks ≤30'); lght sensitivity (-1 atk & vis perc); verm emp +4  

<u>Nualia</u>  
**init**+1; drkvis60, **perc**+5; **ac**18 (t11, ff17); **hp** 59; **f**+10/**r**+3/**w**+8(+9v fear); **resist** 5~~acid~~/~~cold~~/~~elect~~; **sp**30; **+1 bast sw** +10/1d10+4/19, **claw** +3/1d6+1; or **mw c.longbow** +7/1d8+3/x3; **cmb/d**+8/21; *RotRLAA* 61  
**special**: chnl neg engy 6/d (dc15, 2d6), ferocious strike (+2 dmg, 6/d), fury of the Abyss (as swift, +2 akt, dmg & cmb, -2 ac for 1r; 6/d), Lamashtu's Mark (1/d, 1d4 cha dmg, resist dc16), pwr atk, selective channeling  
**spells** (cl6, conc+9): 1/d---daylight; (cl4, conc+7): 2nd---bull's strength, cat's grace, cure mod wnds, shatter (dc15); 1st---divine favor, doom (dc14), obscuring mist, sanctuary (dc14), shield of faith; 0(aw)---bleed (dc13), detect magic, mending, stabilize  
**gear**: +1 breastplate, +1 bast sw, mw c.longbow, 20 arr, gold holy symbol (100gp), 7pp, 5gp  

<u>Orik Vancaskerkin</u>  
**init**+1; **perc**+1; **ac**21 (t11, ff20); **hp** 42; **f**+7/**r**+2/**w**+2(+3 v fear); **sp**30; **mw bastard sword** +9/1d10+5/19 or **c.longbow** +5/1d8+3/×3; **cmb/d**+7/18; *RotRLAA* 55
**special**: power atk, blind-fight  
**gear**: pot cure mod wnds, +1 banded mail, mw hvy st shld, c.longbow, 20 arw, mw bastard swd, everburning torch, 2 pp, 95 gp  

<u>Phycomid</u> cr4; xp1,200  
**init**+0; trmrsns30, **perc**+0; **ac**17 (t11, ff17); **hp**39; **imm** ~~acid~~, mind-affect, prlys, psn, plymrph, sleep, stun; **f**+7/**r**+2/**w**+2; **sp**10; **acid pellet** (rng tch 10') +5/2d6~~acid~~+spores; **cmb/d**+0/10 (no trp); *Best2 210*  
**special**: spores (disease—inj or ing; f:dc15; 1/r for 6r; 1d2 Con dmg; cure 1 sv)  

<u>Red Bishop</u> cr7; xp3,200; adv mothman cl of Pazuzu 1  
**init**+10; drkvis60, **perc**+19; **ac**24 (t16, ff18); **hp** 104; **f**+10/**r**+12/**w**+14; **sr**17; **sp**30, **fl**60 (good);  **2 claws** +15/1d6+3; **cmb/d**+15/28;  
**special**: chnl neg engy 1/d (dc16, 1d6), Agent of Fate 1/d (recreate the effect of any spell <= 5th lvl, but only if doing so steers the flow of fate in its proper course), telepathy 100', Mind-Warping Gaze (30'; trgt shaken 1d6r or 1d4 wis dmg if already feared; w:dc20 neg), Touch of Evil (tch atk, trgt sickened 1r (9/d)), blind-fight, copycat (9/d create single mirror image for 1r), flyby atk (take std act during fly move), stealth +19  
**spells** (cl12, conc+18): const-blur; @will-detect thoughts (dc18), ghst snd (dc16), misdirection; 3/d—gtr invis, mjr img (dc19), modify memory (dc20), nightmare (dc21), phantasmal killer (dc20), shdw walk (dc21), suggestion (dc18); 1/d—agent of fate, false vision, mind fog (dc21), mislead, project img (dc22).
(cl1, conc+7): 1st—bane (dc17), disgs slf, doom (dc17), obscuring mist; 0 (@will)—create water, spark (dc16) x2  

<u>Shadow</u>  
**init**+2; drkvis60, **perc**+8; **ac**15 (t15, ff12); **hp** 19; **f**+3/**r**+3/**w**+4; **fl**40(good); **incorporeal touch** +4/1d6 str dmg; **cmb/d**+4/17; *Best* 245  
**special**: incorporeal; channel resistance+2; undead traits; create spawn (humanoid killed by str dmg becomes a shadow in 1d4r)  

<u>Stormwyrm</u> cr8; xp4800; giant adv tatzlwyrm thunderchild (messed w/terribly so cr is almost certainly wrong)  
**lrg**; **init**+9; drkvis60, ll-vis; **perc**+15; **ac**26 (t18, ff17); **hp**78; **f**+10/**r**+12/**w**+10; **imm** prlys & sleep & inhaled psn & gas, fog, or cloud-based atks & spells; **resist** 10~~cold~~; **sp**30, **cl**30; **bite** +13/2d6+9+1d6~~elec~~+grb; **reach**10; **cmb/d**+14(+18grap)/33(can't be tripped); *Best3* 261, *Adv Best* 237  
**spells** (cl7): 3/d—fog cloud, gaseous form, sound burst(dc19).  
**special**: psn gasp (when grap rpl atk w/psn brth (inh, f:dc18, freq 1/r for 2r, 1d2 str, cure 1 sv), nimble mvs (mv thru 5' of diff terrain as prt of chrg), grb (strat grap for free when hit w/bite), pnce (make rake atks part of chrg), rake (2 claws +12/1d6+9+1d6~~elec~~), lghtnng jmp (may teleport anywhere in area of brth wpn atk), brth wpn (evy 1d4r 3d6~~elec~~ r:dc18 ½, 130x5' ln or 65x10' ln), ~~elec~~ aura (10' 1d6~~elec~~ r:dc18 neg), ~~elec~~ grap (2d6~~elec~~/r when grap), may use spells & ~~elec~~ abilities in gaseous form.  

<u>Tatzlwyrm</u> cr2; xp600  
**init**+2; drkvis60, ll-vis; **perc**+8; **ac**15 (t12, ff13); **hp**22; **f**+4/**r**+5/**w**+5; **imm** prlys & sleep; **sp**30, **cl**30; **bite** +5/1d8+3+grb; **cmb/d**+5(+9grap)/17(can't be tripped); *Best3* 261  
**special**: psn gasp (when grap rpl atk w/psn brth (inh, f:dc12, freq 1/r for 2r, 1d2 str, cure 1 sv), nimble mvs (mv thru 5' of diff terrain as prt of chrg), grb (strat grap for free when hit w/bite), pnce (make rake atks part of chrg), rake (2 claws +12/1d6+9+1d6~~elec~~).  

<u>Telriz the Hatchery Master</u> cr7; xp3200; derro ftr 4  
**init**+6; drkvis60, **perc**+1; **ac**20 (t13, ff18); **hp**77; **f**+11/**r**+4/**w**+8 (+1s. fear); **sr**17; **sp**20; **mw sh swd** +11/+6/1d4+1/19 or **+1 rpt lt xbow** +11/+6/1d6+1/19; **cmb/d**+6/18; *No Resp fm Deepmar* 21  
**spells** (cl3, conc+6): aw-darkness, ghost sound(dc13); 1/d-daze(dc13), sound burst(dc15)  
**special**: snk atk (+1d6); vuln to sun (1 con dmg/h in sunlight); poison use (can't accidentally poin self); cmbt ref (+2); mntd cmbt (1/r if mnt hit, ride chk negates (dc=atk roll)); rd-by atk (cont chrg line aft atk); cytillesh extract (poison, ingested or injury, f:dc18, freq 1/h for 8h, lose memory of events that took place in prev h & can't form new mem for 8h; lost & prevented mem might return later as dreams, & can be returned with restoration or heal spell, cure 2 sv); ride +12; stealth +12  
**gear**: +1 chn sht, +1 rpt lt xbow, mw sh swd, cytillesh extract x5  

<u>Tentamort</u>  
**init**+5; all-arnd vis, blindsense30, drkvis60, **perc**+11; **ac**17 (t11, ff16); **hp** 39; **f**+4/**r**+5/**w**+7; **sp**20, **cl**20; **sting** +6/1d6+2(+poison), **tentacle** +2/1d6+1(+grab); **reach**10; **cmb/d**+6(+10 grap)/17(no trip); *Best2* 261  
**special**: constrict (1d6+1), poison (f:dc15, frq 2r, 1d4 con +nausea, cure 1sav)  

<u>Troglodyte</u> cr1; xp400  
**init**-1; drkvsn90, **perc**+0; **ac**15 (t9, ff15); **hp**13; **f**+7/**r**-1/**w**+0; **sp**30; **club** +2/1d6+1, **claw** -3/1d4, **bite** -3/1d4 or **2 claws** +2/1d4+1, **bite** +2/1d4+1 or **javelin** +0/1d6; **cmb/d**+2/11; *Best* 267  
**special**: stench (30', f:dc13 or sickened 10r)  

<u>Troglodyte hero</u> cr5; xp1600; advanced troglodyte ftr4  
**init**+2; drkvsn90 **perc**+8; **ac**25 (t12, ff23); **hp**61; **f**+13/**r**+3/**w**+3(+4v. fear); **sp**30; **bite**+11/1d4+4, **2 claws**+11/1d4+4 or **jav of lightning** +7/5d6~~elec~~ (r:dc14 ½) **cmb/d**+9/21; *Best* 267  
**special**: stench (30' f:dc17 or sickened 10r), precise stk (+1d6 dmg when flanking w/ally w/ability)  
**gear**: scale arm, jav of lightning  

<u>Troglodyte Chief</u> cr8; xp4800; ½-dragon adv troglodyte ftr 4  
**init**+2; drkvis90, llvis, **perc**+9; **ac**31 (t12, ff29); **hp**89; **f**+16/**r**+4/**w**+4(+5v. fear); **imm** ~~elec~~ & prlys & sleep; **sp**30, **fl**60 (avg); **bite**+16/1d6+8, **2 claws**+16/1d4+8; **cmb/d**+14/26;  
**special**: stench (30', f:dc21 or sickened 10r), brth wpn (1/d 4d6~~elec~~ r:dc19 ½, 60' ln), precise stk (+1d6 dmg when flanking w/ally w/ability)  
**gear**: +1 brstplt  

<u>Troll</u>  
**lrg**; **init**+2; drkvis60, llvis, scent, **perc**+8; **ac**16 (t11, ff14); **hp** 63; **regen** 5 (acid or fire); **f**+11/**r**+4/**w**+3; **sp**30; **bite** +8/1d8+5, **2 claws** +8/1d6+5; **cmb/d**+10/22;  *Best 268*  
**special**: rend (2 claws/1d6+7)  

<i>Troll, Rock</i> cr6; xp2,400  
**lrg**; **init**+1; drkvis60, llvis, scent, **perc**+6; **ac**19 (t10, ff18); **hp**80; **regen**5 (~~acid~~ or ~~sonic~~); **f**+12/**r**+3/**w**+3; **sp**30; **bite** +11/1d8+7, *2 claws** +12/1d6+7; **rch**10; **cmb/d**+13/24; *Best2 272*  
**special**: rend (2 claws, 1d6+9); pwr atk (-2/+4); sun petrif (when exposed to sun, staggered & f:dc20/r to resist permanently petrification. Spells like sunray or sunburst can't petrify, but troll is staggered for 1d4r)  

<u>Tsuto Kaijitsu</u>  
**init**+7; llvis, **perc**+11; **ac**17 (tt17, ff13); **hp** 31; **f**+4/**r**+9/**w**+5(+2v echant); **sp**30; **unarm stk** +5/1d6+1 or **flry blws** +4/+4/1d6+1 or **comp sh bow** +5/1d6+1/x3; **cmb/d**+3/20; *RotRLAA* 31  
**special**: snk atk (+1d6), stun fist (2/d dc14), dflt arw, evasion  
**gear**: pot cur lt wnds, ring prot +1, mw thieves’ tools, mw flute, silver earrings (25gp), 6 pouches gold dust (50gp each), 8 pouches silver dust (5gp each), 10pp  

<u>Yeth Hound</u>  
**init**+6; drkvis60, scent, **perc**+9; **ac**15 (t12, ff13); **hp** 30; **f**+3/**r**+6/**w**+6; **dr**5/slvr; **sp**40, **fl**60(good); **bite**(evil) +7/2d6+4 (+sinister bite & trip); **cmb/d**+7/19(23 trip); *Best* 286  
**special**: bay (300' w:dc12 or panicked 2d4r); sinister bite (good targets w:dc14 or shaken for 1r)  

<u>Warchief Ripnugget</u>  
**init**+2; drkvis60, **perc**-1; **ac** 21 (t13, ff19); **hp** 42; **f**+6/**r**+3/**w**+2 (+1v fear); **sp**30; **+1 sh swd** +10/1d4+5/19; **cmb/d**+5/17; *RotRLAA* 49  
**special**: mntd cmbt (1/r if mnt hit, ride chk negates (dc=atk roll)), rd-by atk (cont chrg line aft atk), sprtd chrg (x2 dmg on chrg (x3 if lance)), ride +12  
**gear**: pot brkskn +2, pot cure mod wnds, mw brstplt, +1 sh swd, dented crown (20gp), keyring for all lock in C11-24 & D1-3  
