<u>Acid Splash</u>  
**Cast Time**: 1 std act  
**Range**: 25' + 5'/2 lvls  
**Save**: none; **SR**: no  
**Desc**: Make a ranged touch attack to hit target. Deals 1d3~~acid~~ dmg. Acid disappears after 1r.  

<u>Bleed</u>  
**Cast Time**: 1 std act  
**Range**: 25' + 5'/2 lvls; **Target**: one living creature;  
**Save**: w:negates; **SR** yes  
**Desc**: Target living creature at < 0 hp but stabilized resumes dying. If target is dying, it takes 1 dmg.  

<u>Bull's Strength</u>  
**Cast Time**: 1 std act  
**Range**: touch; **Duration**: 1m/lvl;  
**Desc**: +4 enhancement bonus to Str.  

<u>Burning Hands</u>  
**Cast Time**: 1 std act  
**Range**: 15' cone  
**Save**: r:½; **SR**: yes  
**Desc**: Creatures in area take 1d4~~fire~~ dmg/caster lvl (max 5d4). Flammable materials burn if flames touch them. Char. can put out flames as f-rnd act.  

<u>Daylight</u>  
**Cast Time**: 1 std act  
**Range**: touch; **Target**: object touched; **Duration**: 10m/lvl  
**Save**: none; **SR** no  
**Desc**: Target sheds bright light in a 60' radius. This increases light lvl for an additional 60' by one step (darkness becomes dim, dim becomes normal, & normal becomes bright). Creatures that take penalties in bright light take them within the initial 60' radius. Daylight brought into an area of magical darkness (or vice versa) is temporarily negated, so that the otherwise prevailing light conditions exist in the overlapping areas of effect.  

<u>Divine Favor</u>  
**Cast Time**: 1 std act  
**Range**: personal; **Duration**: 1m;  
**Desc**: +1/3 lvls (min +1, max +3) luck bonus on atk & dmg (does not apply to spell dmg).  

<u>Doom</u>  
**Cast Time**: 1 std act  
**Range**: 100' + 10'/lvl; **Target**: one living creature; **Duration**: 1m/lvl;  
**Save**: w:negates; **SR**: yes  
**Desc**: Target becomes shaken (–2 on atk, saves, skill checks, & ability checks).  

<u>Flame Blade</u>  
**Cast Time**: 1 std act  
**Duration**: 1m/lvl  
**Saving**: none; **SR**: yes  
**Desc**: Produces a flaming scimitar in hand. Attacks are melee touch attacks. Deals 1d8~~fire~~ +1/2 lvls (max +10). No str bonus to dmg. Can ignite combustible materials.  

<u>Grease</u>  
**Cast Time**: 1 std act  
**Range**: 25' + 5'/2 lvls; **Target**: 1 obj or 10' sq.; **Duration**: 1m/lvl  
**Save**: see text; **SR**: no  
**Desc**:  
- Creatures in area when cast, Ref save or fall. Creature can walk in or through area @½ speed w/Acrobatics dc:10. Failure means it can't move that round (and must a Ref save or fall), while failure by 5 or more means it falls.
- Or to create a greasy coating on an item. Objects not in use are always affected, while objects wielded require their bearers to make a Ref save to avoid the effect. If initial save fails, creature drops item. A save must be made each round that the creature attempts to pick up or use the item. A creature wearing greased armor or clothing gains a +10 circumstance bonus on Escape Artist checks and combat maneuver checks made to escape a grapple, and to their CMD to avoid being grappled.  

<u>Invisibility</u>  
**Cast Time**: 1 std act  
**Range**: pers or tch; **Target**: you or creature or object weighing ≤ 100 lbs./lvl; **Duration**: 1m/lvl  
**Desc**: Target & gear become invisible. If you cast the spell on someone else, neither you nor your allies can see the subject, unless you can normally see invisible things or you employ magic to do so. Items dropped become visible; items picked up disappear if tucked into the clothing or pouches. Light, however, never becomes invisible. If check required, a stationary creature gets +40 on Stealth checks (+20 if moving). Spell ends if subject attacks (including offensive spells).  

<u>Mage Armor</u>  
**Cast Time**: 1 std act  
**Range**: touch; **Target**: creature touched; **Duration**: 1h/lvl  
**Desc**: +4 armor bonus to AC. This is a force effect and incorporeal creatures can't bypass.  

<u>Mirror Image</u>  
**Cast Time**: 1 std act  
**Range**: personal; **Target**: you; **Duration**: 1m/lvl  
**Desc**: 1d4 images +1/3 lvls (max 8 total) are created. If target is attacked determine randomly of target or a figment is hit. If an attack misses by 5 or less, a figment is hit. Hit figments are destroyed.  

<u>Obscuring Mist</u>
**Cast Time**: 1 std act  
**Range**: 20'; **Effect**: cloud 20' radius from you, 20' high; **Duration**: 1m/lvl  
**Save**: none; **SR**: no  
**Desc**: Stationary cloud obscures all sight, including darkvision, beyond 5'. A creature 5' away has concealment (20% miss chance). Creatures farther away have total concealment (50% miss chance, and the attacker cannot use sight to locate the target).  Moderate wind (11+ mph), such as from a gust of wind spell, disperses the fog in 4r. Strong wind (21+ mph) disperses the fog in 1r. A fireball, flame strike, or similar burns away the fog in the spell's area.  

<u>Produce Flame</u>  
**Cast Time**: 1 std act  
**Range**: tch or 120'; **Duration**: 1m/lvl  
**Save**: none; **SR**: yes  
Flames as bright as torch appear in hand (harm neither you nor your equipment). Can strike opponent w/melee touch attack, dealing 1d6~~fire~~+1/lvl (max +5). Or, hurl flames up to 120' as ranged touch attack. Flames reappear in hand. Each ranged attack reduces duration by 1m.  

<u>Ray of Enfeeblement</u>  
**Cast Time**: 1 std act  
**Range**: 25' + 5'/2 lvls; **Duration**: 1r/lvl  
**Save**: f:½; **SR**: yes  
**Desc**: Make ranged tch atk. Target takes str penalty of 1d6+1/2 lvls (max 1d6+5). Target's str can't drop below 1.  

<u>Ray of Frost</u>  
**Cast Time**: 1 std act  
**Range**: 25' + 5'/2 lvls  
**Save**: none; **SR**: yes  
**Desc**: Make ranged tch atk. Target takes 1d3~~cold~~ dmg.  

<u>Sanctuary</u>  
**Cast Time**: 1 std act  
**Range**: touch; **Target**: creature touched; **Duration**: 1r/lvl;  
**Save**: w:negates; **SR**: no  
**Desc**: Attacking opponents must make a Will save. Failure means the attack fails and it can't attack for duration of spell. If subject attacks, spell ends.  

<u>Shatter</u>  
**Cast Time**: 1 std act    
**Range**: 25' + 5'/2 lvls; **Target**: 5' radius spread; or 1 solid object or 1 crystalline creature  
**Save**: w:negates (object); w:negates (object) or f:½; see text; **SR**: yes  
**Desc**: 
- As area atk, shatter destroys nonmagical objects of crystal, glass, ceramic, or porcelain. All objects in a 5' radius are smashed into dozens of pieces. Objects weighing more than 1 lb/lvl are not affected. 
- Or target a single solid nonmagical object, regardless of composition, weighing up to 10 lbs/lvl.
- Or target a crystalline creature (of any weight). Deals 1d6~~sonic~~ damage per caster level (max 10d6), with f:½.  

<u>Shield of Faith</u>  
**Cast Time**: 1 std act  
**Range**: touch; **Target**: creature touched; **Duration**: 1m/lvl;  
**Desc**: +2 deflection to AC, +1/6 lvls (max +5 & 18th). 

<u>Stabilize</u>  
**Cast Time**: 1 std act  
**Range**: 25' + 5'/2 lvls; **Target**: one living creature;  
**Desc**: Target w/≤ -1 hp automatically stabilizes.  
